name: 'energy'
version: '1.0.0'
config-version: 2

profile: 'energy'

model-paths: ["models"]
test-paths: ["tests"]

models:
  energy:
    staging:
      materialized: view
    mart:
      materialized: table