services:

  postgres:
    image: postgres:15
    container_name: energy_postgres
    environment:
      POSTGRES_USER: energy_user
      POSTGRES_PASSWORD: energy_pass
      POSTGRES_DB: energy_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: energy_minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped

  airflow-db:
    image: postgres:15
    container_name: energy_airflow_db
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  airflow-init:
    image: apache/airflow:2.9.1
    container_name: energy_airflow_init
    depends_on:
      - airflow-db
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db/airflow
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: 'admin'
      _AIRFLOW_WWW_USER_PASSWORD: 'admin'
      _AIRFLOW_WWW_USER_FIRSTNAME: 'Mehdi'
      _AIRFLOW_WWW_USER_LASTNAME: 'DE'
      _AIRFLOW_WWW_USER_EMAIL: 'admin@energy.com'
      _AIRFLOW_WWW_USER_ROLE: 'Admin'
    command: version
    restart: on-failure

  airflow-webserver:
    image: apache/airflow:2.9.1
    container_name: energy_airflow_webserver
    depends_on:
      - airflow-db
      - airflow-init
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db/airflow
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__WEBSERVER__SECRET_KEY: 'energy_secret'
      _PIP_ADDITIONAL_REQUIREMENTS: 'httpx pandas pyarrow python-dotenv loguru boto3'
      MINIO_ENDPOINT: 'http://minio:9000'
      MINIO_ROOT_USER: 'minioadmin'
      MINIO_ROOT_PASSWORD: 'minioadmin123'
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./ingestion:/opt/airflow/ingestion
      - ./storage:/opt/airflow/storage
      - airflow_logs:/opt/airflow/logs
    command: webserver
    restart: unless-stopped

  airflow-scheduler:
    image: apache/airflow:2.9.1
    container_name: energy_airflow_scheduler
    depends_on:
      - airflow-db
      - airflow-init
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db/airflow
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      _PIP_ADDITIONAL_REQUIREMENTS: 'httpx pandas pyarrow python-dotenv loguru boto3'
      MINIO_ENDPOINT: 'http://minio:9000'
      MINIO_ROOT_USER: 'minioadmin'
      MINIO_ROOT_PASSWORD: 'minioadmin123'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./ingestion:/opt/airflow/ingestion
      - ./storage:/opt/airflow/storage
      - airflow_logs:/opt/airflow/logs
    command: scheduler
    restart: unless-stopped

  metabase:
    image: metabase/metabase:latest
    container_name: energy_metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: energy_user
      MB_DB_PASS: energy_pass
      MB_DB_HOST: postgres
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
  minio_data:
  airflow_db_data:
  airflow_logs: